# Generated by Django 5.1.7 on 2025-11-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_inventorycategory_inventoryitem_bookinginventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
