# Generated by Django 5.1.7 on 2025-11-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_inventorycategory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-id']},
        ),
    ]
