# Generated by Django 5.1.7 on 2025-11-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_booking_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ManyToManyField(to='core.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(to='core.service'),
        ),
    ]
