# Generated by Django 5.1.7 on 2025-11-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_booking_customer_remove_booking_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.TextField(blank=True, null=True),
        ),
    ]
