# Generated by Django 5.1.7 on 2025-12-02 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_booking_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='barangay',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default='Lucena City', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='street',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('gcash', 'GCash'), ('paymaya', 'Paymaya'), ('bank', 'Bank Transfer'), ('other', 'Oher')], help_text='Payment method used (GCash, PayMaya, etc.)', max_length=50, null=True),
        ),
    ]
